apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  name: my-okd-cluster-name-XXXXX-infra
  namespace: openshift-machine-api
spec:
  replicas: 1
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: my-okd-cluster-name-XXXXX
      machine.openshift.io/cluster-api-machineset: my-okd-cluster-name-XXXXX-infra
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: my-okd-cluster-name-XXXXX
        machine.openshift.io/cluster-api-machine-role: infra
        machine.openshift.io/cluster-api-machine-type: infra
        machine.openshift.io/cluster-api-machineset: my-okd-cluster-name-XXXXX-infra
    spec:
      metadata:
       labels:
          node-role.kubernetes.io/infra: ""
      providerSpec:
        value:
          apiVersion: vsphereprovider.openshift.io/v1beta1
          credentialsSecret:
            name: vsphere-cloud-credentials
          diskGiB: 120
          kind: VSphereMachineProviderSpec
          memoryMiB: 24576
          metadata:
            creationTimestamp: null
          network:
            devices:
            - networkName: my-vlan-network-name
          numCPUs: 4
          numCoresPerSocket: 1
          snapshot: ""
          template: okd-cluster-name-XXXXX-rhcos
          userDataSecret:
            name: worker-user-data
          workspace:
            datacenter: my-datacenter
            datastore: my-datastore
            folder: /path/to/my-okd-cluster-name-XXXXX
            resourcePool: my-resource-pool
            server: my-vcenter_fqdn